// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Panoptes.Infrastructure.Persistence;

#nullable disable

namespace Panoptes.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251212153806_AddSoftDelete")]
    partial class AddSoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Panoptes.Core.Entities.DeliveryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRateLimitRetry")
                        .HasColumnType("boolean");

                    b.Property<double>("LatencyMs")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("integer");

                    b.Property<int?>("RetryAfterSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt")
                        .HasDatabaseName("IX_DeliveryLogs_AttemptedAt");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("IX_DeliveryLogs_SubscriptionId");

                    b.HasIndex("SubscriptionId", "AttemptedAt")
                        .HasDatabaseName("IX_DeliveryLogs_SubscriptionId_AttemptedAt");

                    b.ToTable("DeliveryLogs");
                });

            modelBuilder.Entity("Panoptes.Core.Entities.DemeterConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrpcEndpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Network")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Preprod");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_DemeterConfigs_IsActive");

                    b.ToTable("DemeterConfigs");
                });

            modelBuilder.Entity("Panoptes.Core.Entities.SystemState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SystemStates");
                });

            modelBuilder.Entity("Panoptes.Core.Entities.WebhookSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BatchWindowSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("CircuitBrokenReason")
                        .HasColumnType("text");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EnableBatching")
                        .HasColumnType("boolean");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FirstFailureInWindowAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCircuitBroken")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRateLimited")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSyncing")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastWebhookAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxWebhooksPerHour")
                        .HasColumnType("integer");

                    b.Property<int>("MaxWebhooksPerMinute")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MinimumLovelace")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PolicyId")
                        .HasColumnType("text");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetAddress")
                        .HasColumnType("text");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WalletAddresses")
                        .HasColumnType("jsonb");

                    b.Property<int>("WebhooksInLastHour")
                        .HasColumnType("integer");

                    b.Property<int>("WebhooksInLastMinute")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WebhookSubscriptions");
                });

            modelBuilder.Entity("Panoptes.Core.Entities.DeliveryLog", b =>
                {
                    b.HasOne("Panoptes.Core.Entities.WebhookSubscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
