-- Migration: Add pause functionality to subscriptions
-- Purpose: Allow users to temporarily pause webhook deliveries without losing pending events
-- Date: 2024-12-08
-- Note: Pause state is tracked using the existing IsActive column
